name: Pull Request
description: ""
title: "[Bug]: <title>"
labels: ["bug", "triage"]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "Please include a summary of the change and which issue is fixed. Please also include relevent motivation and context. List any dependencies that are required for this change.

        Please delete options options that are not relevent and please make sure that you X the appropriate boxes.

        Fixes # (issue)"
      placeholder: ""
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Type of Change"
      description: ""
      options:
        - label: "Bug fix (non-breaking change which fixes an issue)"
        - label: "New feature (non-breaking change which adds functionality)"
        - label: "Breaking change (fix or feature that would cause existing functionality to not work as expected)"
        - label: "This change requires a documentation update"
          required: true






  - type: checkboxes
    attributes:
      label: "Type of Change"
      description: ""
      options:
        - label: ""
        - label: ""
          required: true
  - type: textarea
    attributes:
      label: ""
      description: ""
      placeholder: ""
    validations:
      required: false
