name: 🐛 Bug Report
description: Create a bug report to help us improve this project
title: "[Bug]: <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check existing issues
        _Before submitting an issue_ please search [existing issues](https://github.com/gbowne1/reactsocialnetwork/issues) to see if an issue your bug already exists
  - type: checkboxes
    attributes:
      label: null
      options:
        - label: I have searched the existing issues
          required: true
  - type: markdown
    attributes:
      value: |
        ## Bug Description
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is and the expected behaviour
    validations: 
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: |
       Drag and drop image here
                        OR
       Click the textarea then "Attach files"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Device
  - type: input
    id: device
    attributes:
      label: Which device are you using?
      placeholder: e.g. PC, MacBook Pro, iPhone 8, Galaxy S23
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Which operating system are you using?
      placeholder: e.g. Linux, Mac, Windows, iOS, Android
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Which browser are you using?
      placeholder: e.g. Chrome, Safari, Firefox
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Additional Context
    validations:
      required: false
  - type: checkboxes
    id: can-contribute
    attributes:
      label: Contribute
      options:
        - label: I am willing to contribute and submit a pull request
          required: false
