name: Bug Report
description: Create a bug report to help us improve this project
title: "[Bug]: <title>"
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Have you checked if there is an existing issue for this?
      description: Please search to see if an issue already exists for the bug you have encountered
      options:
        - label: I have searched the existing issues
          required: true

