name: Bug Report
description: Create a bug report to help us improve this project
title: "[Bug]: <title>"
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Have you checked if there is an existing issue for this?
      description: Please search to see if an issue already exists for the bug you have encountered
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      validations:
        required: false
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what can be expected to happen.
      validations: false
  - type: textarea
    attributes:
      description: If applicable, add screenshots to help explain your problem
      validations:
        required: false

