blank_issues_enabled: true
contact_links:
  - name: Slack
    url: https://join.slack.com/t/reactsocialmediadev/shared_invite/zt-1qxkurpk1-xP5wRx3oaCauIXBmt1ToVA
    about: Join the discussion on our Slack channel
