name: Feature Request
description: Suggest an idea for this project
title: "[feature]: <title>"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: "## Is your feature request related to a problem? Please describe."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Required"
      description: "A clear and concise description of what the problem is. Ex. I am always frustrated when [...]"
      placeholder: Description
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Describe the solution you would like"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Required"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Solution"
    validations: 
      required: true
  - type: markdown
    attributes:
      value: "## Describe the alternatives you have tried"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "## Required"
      description: "A clear and concise description of any alternative solutions or features you have considered."
      placeholder: "Alternatives"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Additional context"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Required"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Additional context"
    validations:
      required: false
