name: Feature Request
description: Suggest an idea for this project
title: "[feature]: <title>"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. I am always frustrated when [...]"
      placeholder: |
        Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the solution you would like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Solution"
    validations: 
      required: true
  - type: textarea
    attributes:
      label: "Describe the alternatives you have tried"
      description: "A clear and concise description of any alternative solutions or features you have considered."
      placeholder: "Alternatives"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Additional context"
    validations:
      required: false
